#@ load("@ytt:data", "data")
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ data.values.name
  labels: #@ data.values.defaultLabels
  annotations:
    kubernetes.io/ingress.global-static-ip-name: #@ data.values.static_ip
    networking.gke.io/v1beta1.FrontendConfig: #@ data.values.name
    #@ certificates = []
    #@ for i in range(len(data.values.sites)):
    #@ certificates.append(data.values.name + "-managed-cert-" + str(i))
    #@ end
    networking.gke.io/managed-certificates: #@ ','.join(certificates)
spec:
  rules:
#@ arr = data.values.sites
#@ for i in arr:
  - host: #@ i
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: #@ data.values.name
            port:
              number: 80
#@ end
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: #@ data.values.name
  labels: #@ data.values.defaultLabels
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "PERMANENT_REDIRECT"
#@ arr = data.values.sites
#@ for i in range(len(arr)):
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: #@ data.values.name + "-managed-cert-" + str(i)
spec:
  domains: #@ [arr[i]]
#@ end